# Generated by Django 3.2.3 on 2021-05-28 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_subcomment_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subcomment',
        ),
    ]
