# Generated by Django 3.2.3 on 2021-05-24 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news/')),
                ('title', models.CharField(max_length=200)),
                ('text_1', models.TextField()),
                ('quote', models.CharField(max_length=200)),
                ('text_2', models.TextField()),
            ],
        ),
    ]
