# Generated by Django 3.2.3 on 2021-05-24 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_image', models.ImageField(upload_to='about/')),
                ('text_about', models.TextField()),
                ('title_about', models.TextField()),
                ('text_1', models.TextField()),
                ('text_2', models.TextField()),
                ('text_3', models.TextField()),
                ('image_1', models.ImageField(upload_to='about/')),
                ('image_2', models.ImageField(upload_to='about/')),
                ('image_3', models.ImageField(upload_to='about/')),
                ('image_4', models.ImageField(upload_to='about/')),
                ('image_5', models.ImageField(upload_to='about/')),
                ('image_6', models.ImageField(upload_to='about/')),
                ('image_7', models.ImageField(upload_to='about/')),
                ('image_8', models.ImageField(upload_to='about/')),
            ],
        ),
    ]
